dir: mewbot
override_dir:
env:
  - "env/bot.env"
  - "env/mongo.env"
  - "env/postgres.env"
  - "env/voting.env"
names: assets/data/names.txt
module: mew
redis: 178.28.0.13:6379
redis_channel: mewbot_clusters
interp: /usr/bin/python3.10